export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCES = "GET_CATEGORIES_SUCCES";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const GET_CATEGORIE_REQUEST = "GET_CATEGORIE_REQUEST";
export const GET_CATEGORIE_SUCCES = "GET_CATEGORIE_SUCCES";
export const GET_CATEGORIE_FAIL = "GET_CATEGORIE_FAIL";

export const ADD_CATEGORIE_REQUEST = "ADD_CATEGORIE_REQUEST";
export const ADD_CATEGORIE_SUCCES = "ADD_CATEGORIE_SUCCES";
export const ADD_CATEGORIE_FAIL = "ADD_CATEGORIE_FAIL";

export const UPDATE_CATEGORIE_REQUEST = "UPDATE_CATEGORIE_REQUEST";
export const UPDATE_CATEGORIE_SUCCES = "UPDATE_CATEGORIE_SUCCES";
export const UPDATE_CATEGORIE_FAIL = "UPDATE_CATEGORIE_FAIL";

export const DELETE_CATEGORIE_REQUEST = "DELETE_CATEGORIE_REQUEST";
export const DELETE_CATEGORIE_SUCCES = "DELETE_CATEGORIE_SUCCES";
export const DELETE_CATEGORIE_FAIL = "DELETE_CATEGORIE_FAIL";
