export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCES = "GET_POST_SUCCES";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST";
export const GET_SINGLE_POST_SUCCES = "GET_SINGLE_POST_SUCCES";
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL";
